import Link from 'next/link';
import { ArrowRight, HeartPulse, Layers3, Shield, Workflow } from 'lucide-react';
import { PageContainer } from '@/components/ui/common/pageContainer';
import { Button } from '@/components/ui/button';

const pillars = [
  {
    title: 'One place for adjacent decisions',
    body: 'Scans, medicines, second opinions, treatment planning, and hospital search sit next to each other because that is how the questions actually arrive.',
    icon: Workflow,
  },
  {
    title: 'Structured output over vague prose',
    body: 'We shape model responses into predictable sections so the UI can present them clearly and help users compare options instead of parsing blobs of text.',
    icon: Layers3,
  },
  {
    title: 'Open infrastructure where it matters',
    body: 'Maps run on OSM and hospital lookup is directory-driven. The product avoids expensive platform lock-in where open alternatives are strong enough.',
    icon: Shield,
  },
];

export default function AboutPage() {
  return (
    <PageContainer className="space-y-8">
      <section className="soft-panel overflow-hidden">
        <div className="grid gap-6 px-6 py-8 sm:px-8 sm:py-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
          <div className="space-y-4">
            <span className="eyebrow">about the product</span>
            <h1 className="text-4xl text-foreground sm:text-5xl">Sonarive is a health workflow workspace, not a one-shot AI toy.</h1>
            <p className="support-copy max-w-3xl">
              The rebuild focuses on clearer structure, lighter infrastructure, and UI that feels closer to a real product studio than an autogenerated template pack.
            </p>
          </div>
          <div className="rounded-[24px] border border-border/70 bg-background/70 p-5">
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-muted-foreground">Operating idea</p>
            <p className="mt-3 text-sm leading-7 text-muted-foreground">
              When users need help, they usually need more than one answer: a scan summary, treatment questions, medication context, and where to go next. Sonarive is designed around that chain.
            </p>
          </div>
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-3">
        {pillars.map((pillar) => {
          const Icon = pillar.icon;
          return (
            <article key={pillar.title} className="soft-panel p-6">
              <div className="inline-flex rounded-2xl bg-primary/10 p-3 text-primary">
                <Icon className="h-5 w-5" />
              </div>
              <h2 className="mt-4 text-3xl text-foreground">{pillar.title}</h2>
              <p className="mt-3 text-sm leading-7 text-muted-foreground">{pillar.body}</p>
            </article>
          );
        })}
      </section>

      <section className="grid gap-4 lg:grid-cols-[0.9fr_1.1fr]">
        <div className="soft-panel p-6 sm:p-8">
          <span className="eyebrow">product stance</span>
          <h2 className="mt-4 text-4xl text-foreground">What changed in the rebuild</h2>
          <ul className="mt-5 space-y-3 text-sm leading-7 text-muted-foreground">
            <li>Groq replaces older provider experiments for a simpler single-key AI backend.</li>
            <li>Maps stay fully open-source with Leaflet and OpenStreetMap data.</li>
            <li>Page structure, spacing, typography, and cards are now uniform across the app.</li>
            <li>Results are presented in sections that help users verify before acting.</li>
          </ul>
        </div>
        <div className="soft-panel p-6 sm:p-8">
          <div className="flex items-center gap-3">
            <HeartPulse className="h-5 w-5 text-accent" />
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-muted-foreground">next step</p>
          </div>
          <h2 className="mt-4 text-4xl text-foreground">Start inside a real workflow</h2>
          <p className="mt-4 text-sm leading-7 text-muted-foreground">
            The best way to understand the product is to use one of the decision flows. Start with imaging if you have a scan, or go straight to treatment planning if you already have a diagnosis in hand.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Button asChild className="rounded-full px-6">
              <Link href="/scan">Open scan analysis</Link>
            </Button>
            <Button asChild variant="outline" className="rounded-full px-6">
              <Link href="/treatmentPlans">
                Treatment planner
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </PageContainer>
  );
}
